    setInCampaign("wolverine", "TRUE")
    setInCampaign("cyclops", "TRUE")
    setInCampaign("storm", "TRUE")
    setInCampaign("phoenix", "TRUE")
    setInCampaign("beast", "TRUE")
    setInCampaign("iceman", "TRUE")
