# Generated by BehavEd
# ( "tank1" )
lockControls(-1.000 )
setCombatNode("_HERO1_", "idle" )
setCombatNode("_HERO2_", "idle" )
setCombatNode("_HERO3_", "idle" )
setCombatNode("_HERO4_", "idle" )
setallaiactive("FALSE" )
screenFade(1.000, 0.500 )
waittimed ( 0.500 )
act("subway_sound", "subway_sound" )
setEnable("subway_sound", "FALSE" )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "null13" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "null13_p2" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "null13_p3" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "null13_p4" )
endif
cameraToLocationAngles(" 826.530 1919.931 370.339 ", " 920.000 1920.000 0.000 ", 0.000 )
waittimed ( 0.100 )
setPartyLightColor(" 0.000 0.000 0.000 ", 1.000 )
cameraResetOldSchool( )
screenFade(0.000, 0.500 )
waittimed ( 0.500 )
setallaiactive("TRUE" )
lockControls(0.100 )

