# Generated by BehavEd
# ( "subway up A" )
lockControls(-1.000 )
setCombatNode("_HERO1_", "idle" )
setCombatNode("_HERO2_", "idle" )
setCombatNode("_HERO3_", "idle" )
setCombatNode("_HERO4_", "idle" )
setallaiactive("FALSE" )
screenFade(1.000, 1.000 )
waittimed ( 1.000 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "subway_upa" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "subway_upa_p2" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "subway_upa_p3" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "subway_upa_p4" )
endif
cameraToLocationAngles(" 2280.000 2440.655 279.896 ", " 2280.000 2544.443 0.000 ", 0.000 )
waittimed ( 0.100 )
setPartyLightColor(" 0.000 0.000 0.000 ", 1.000 )
cameraResetOldSchool( )
screenFade(0.000, 1.000 )
waittimed ( 1.000 )
setallaiactive("TRUE" )
lockControls(0.100 )

