# Generated by BehavEd
# ( "tank1" )
lockControls(-1.000 )
setCombatNode("_HERO1_", "idle" )
setCombatNode("_HERO2_", "idle" )
setCombatNode("_HERO3_", "idle" )
setCombatNode("_HERO4_", "idle" )
setallaiactive("FALSE" )
screenFade(1.000, 0.500 )
waittimed ( 0.500 )
setEnable("subway_sound", "TRUE" )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "null05" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "null05_p2" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "null05_p3" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "null05_p4" )
endif
cameraToLocationAngles(" 947.756 3215.718 115.481 ", " 828.630 3215.932 -205.004 ", 0.000 )
waittimed ( 0.100 )
setPartyLightColor(" 0.870 0.940 1.000 ", 1.000 )
cameraResetOldSchool( )
screenFade(0.000, 0.500 )
waittimed ( 0.500 )
setallaiactive("TRUE" )
lockControls(0.100 )

