# Generated by BehavEd
# ( "subway up A" )
lockControls(-1.000 )
setCombatNode("_HERO1_", "idle" )
setCombatNode("_HERO2_", "idle" )
setCombatNode("_HERO3_", "idle" )
setCombatNode("_HERO4_", "idle" )
setallaiactive("FALSE" )
screenFade(1.000, 1.000 )
waittimed ( 1.000 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "subway_downa" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "subway_downa_p2" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "subway_downa_p3" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "subway_downa_p4" )
endif
cameraToLocationAngles(" 660.000 1024.260 172.112 ", " 660.000 960.062 -168.956 ", 0.000 )
waittimed ( 0.100 )
setPartyLightColor(" 0.870 0.940 1.000 ", 1.000 )
cameraResetOldSchool( )
screenFade(0.000, 1.000 )
waittimed ( 1.000 )
setallaiactive("TRUE" )
lockControls(0.100 )

